### ISSUE TITLE
kicommand in KiCAD 5.1

### ISSUE THREAD

**Issue by xyybob** [HiGregSmith/KiCommand#3]
I've tried 'import kicommand' in the script window but I'm having problems with not finding 'CPolyLine' and kicommand doesn't import. This is what I get:

import kicommand
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\KiCad\share\kicad\scripting\plugins/kicommand/__init__.py", line 2, in <module>
    from .kicommand import *
  File "C:\Program Files\KiCad\share\kicad\scripting\plugins/kicommand/kicommand.py", line 1543, in <module>
    def newzone(points, netname, layer, CPolyLine=pcbnew.CPolyLine.NO_HATCH, priority=0):
AttributeError: 'module' object has no attribute 'CPolyLine'

I want to put text into a Cu layer. How do I get this to work?

**Comment by lvsoft** [comment]
That's because api changes in pcbnew.
I created a PR to porting kicommand to python3 ( and KiCAD 5.1 ), which should solve this issue: https://github.com/HiGregSmith/KiCommand/pull/4

However, this port is far from finished, it will import, but you may encouter other issues.

**Comment by HiGregSmith** [comment]
The latest updated to KiCommand attempts to be compatible with python3 (and python2, since my copy of KiCAD (5.1.5)-3 release is still using python2.7. Unfortunately the tests (when using **import kicommand.test** from the Scripting Console) are not yet python3 compatible. Please let me know if there are any problems.
